name: perfect_loader_example
description: Example app for perfect_loader.
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  perfect_loader:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
